language: python
branches:
  only:
  - master
before_install:
- pip install mkdocs
script:
- mkdocs build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: site
  target-branch: gh-pages
  on:
    branch: master